# Generated by Django 3.1.4 on 2021-01-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('konten', models.TextField(null=True)),
                ('penulis', models.CharField(max_length=64, null=True)),
                ('tanggaldibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentator', models.CharField(max_length=64, null=True)),
                ('komentar', models.TextField(null=True)),
                ('thread_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.thread')),
            ],
        ),
    ]
